<a href="https://colab.research.google.com/github/sonikab2025/fds-lab-record/blob/main/EXP_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:



import numpy as np
import pandas as pd

# Create hotel dataset without CSV

data = {
"CustomerID": [1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 10],
"Age_Group": [
"20-25", "30-35", "25-30", "20-25", "35+",
"35+", "35+", "20-25", "25-30", "25-30", "30-35"
],
"Rating(1-5)": [4, 5, 6, -1, 3, 3, 4, 7, 2, 2, 5],
"Hotel": [
"Ibis", "LemonTree", "RedFox", "LemonTree", "Ibis",
"Ibys", "RedFox", "LemonTree", "Ibis", "Ibis", "RedFox"
],
"FoodPreference": [
"veg", "Non-Veg", "Veg", "Veg", "Vegetarian",
"Non-Veg", "Vegetarian", "Veg", "Non-Veg",
"Non-Veg", "non-Veg"
],
"Bill": [1300, 2000, 1322, 1234, 989, 1909, 1000, 2999, 3456, 3456, 6755],
"NoOfPax": [2, 3, 2, 2, 2, 2, -1, -10, 3, 3, 4],
"EstimatedSalary": [
40000, 59000, 30000, 120000, 45000, 122220,
21122, 345673, -99999, -99999, 87777
],
"Age_Group.1": [
"20-25", "30-35", "25-30", "20-25", "35+",
"35+", "35+", "20-25", "25-30", "25-30", "30-35"
]
}

df = pd.DataFrame(data)

# Display the complete DataFrame
print(df)

    CustomerID Age_Group  Rating(1-5)      Hotel FoodPreference  Bill  \
0            1     20-25            4       Ibis            veg  1300
1            2     30-35            5  LemonTree        Non-Veg  2000
2            3     25-30            6     RedFox            Veg  1322
3            4     20-25           -1  LemonTree            Veg  1234
4            5       35+            3       Ibis     Vegetarian   989
5            6       35+            3       Ibys        Non-Veg  1909
6            7       35+            4     RedFox     Vegetarian  1000
7            8     20-25            7  LemonTree            Veg  2999
8            9     25-30            2       Ibis        Non-Veg  3456
9            9     25-30            2       Ibis        Non-Veg  3456
10          10     30-35            5     RedFox        non-Veg  6755

    NoOfPax  EstimatedSalary Age_Group.1
0         2            40000       20-25
1         3            59000       30-35
2         2            30000       25-30
3         2           120000       20-25
4         2            45000         35+
5         2           122220         35+
6        -1            21122         35+
7       -10           345673       20-25
8         3           -99999       25-30
9         3           -99999       25-30
10        4            87777       30-35

In [3]:
print(df.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
dtype: bool

In [4]:

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       11 non-null     int64
 1   Age_Group        11 non-null     object
 2   Rating(1-5)      11 non-null     int64
 3   Hotel            11 non-null     object
 4   FoodPreference   11 non-null     object
 5   Bill             11 non-null     int64
 6   NoOfPax          11 non-null     int64
 7   EstimatedSalary  11 non-null     int64
 8   Age_Group.1      11 non-null     object
dtypes: int64(5), object(4)
memory usage: 924.0+ bytes
None

In [5]:

df.drop_duplicates(inplace=True)
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary,Age_Group.1
0,1,20-25,4,Ibis,veg,1300,2,40000,20-25
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000,30-35
2,3,25-30,6,RedFox,Veg,1322,2,30000,25-30
3,4,20-25,-1,LemonTree,Veg,1234,2,120000,20-25
4,5,35+,3,Ibis,Vegetarian,989,2,45000,35+
5,6,35+,3,Ibys,Non-Veg,1909,2,122220,35+
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122,35+
7,8,20-25,7,LemonTree,Veg,2999,-10,345673,20-25
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999,25-30
10,10,30-35,5,RedFox,non-Veg,6755,4,87777,30-35

In [6]:

len(df)

10

In [7]:
index = np.array(list(range(0, len(df))))
df.set_index(index, inplace=True)
index
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary,Age_Group.1
0,1,20-25,4,Ibis,veg,1300,2,40000,20-25
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000,30-35
2,3,25-30,6,RedFox,Veg,1322,2,30000,25-30
3,4,20-25,-1,LemonTree,Veg,1234,2,120000,20-25
4,5,35+,3,Ibis,Vegetarian,989,2,45000,35+
5,6,35+,3,Ibys,Non-Veg,1909,2,122220,35+
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122,35+
7,8,20-25,7,LemonTree,Veg,2999,-10,345673,20-25
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999,25-30
9,10,30-35,5,RedFox,non-Veg,6755,4,87777,30-35

In [8]:

df.drop(['Age_Group.1'], axis=1, inplace=True)
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1,20-25,4,Ibis,veg,1300,2,40000
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000
2,3,25-30,6,RedFox,Veg,1322,2,30000
3,4,20-25,-1,LemonTree,Veg,1234,2,120000
4,5,35+,3,Ibis,Vegetarian,989,2,45000
5,6,35+,3,Ibys,Non-Veg,1909,2,122220
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122
7,8,20-25,7,LemonTree,Veg,2999,-10,345673
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999
9,10,30-35,5,RedFox,non-Veg,6755,4,87777

In [9]:
df.loc[(df['Rating(1-5)'] < 1) | (df['Rating(1-5)'] > 5), 'Rating(1-5)'] = np.nan
df.loc[df['CustomerID'] < 0, 'CustomerID'] = np.nan
df.loc[df['Bill'] < 0, 'Bill'] = np.nan
df.loc[df['EstimatedSalary'] < 0, 'EstimatedSalary'] = np.nan
df.loc[(df['NoOfPax'] < 1) | (df['NoOfPax'] > 20), 'NoOfPax'] = np.nan
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1.0,20-25,4.0,Ibis,veg,1300.0,2.0,40000.0
1,2.0,30-35,5.0,LemonTree,Non-Veg,2000.0,3.0,59000.0
2,3.0,25-30,NaN,RedFox,Veg,1322.0,2.0,30000.0
3,4.0,20-25,NaN,LemonTree,Veg,1234.0,2.0,120000.0
4,5.0,35+,3.0,Ibis,Vegetarian,989.0,2.0,45000.0
5,6.0,35+,3.0,Ibys,Non-Veg,1909.0,2.0,122220.0
6,7.0,35+,4.0,RedFox,Vegetarian,1000.0,NaN,21122.0
7,8.0,20-25,NaN,LemonTree,Veg,2999.0,NaN,345673.0
8,9.0,25-30,2.0,Ibis,Non-Veg,3456.0,3.0,NaN
9,10.0,30-35,5.0,RedFox,non-Veg,6755.0,4.0,87777.0

In [10]:
df['Hotel'] = df['Hotel'].replace(['Ibys'], 'Ibis')
df['FoodPreference'] = df['FoodPreference'].replace(['Vegetarian', 'veg'], 'Veg')
df['FoodPreference'] = df['FoodPreference'].replace(['non-Veg'], 'Non-Veg')
df['EstimatedSalary'] = df['EstimatedSalary'].fillna(round(df['EstimatedSalary'].mean()))
df['Bill'] = df['Bill'].fillna(round(df['Bill'].mean()))
df['NoOfPax'] = df['NoOfPax'].fillna(round(df['NoOfPax'].median()))
df['Rating(1-5)'] = df['Rating(1-5)'].fillna(round(df['Rating(1-5)'].median()))
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1.0,20-25,4.0,Ibis,Veg,1300.0,2.0,40000.0
1,2.0,30-35,5.0,LemonTree,Non-Veg,2000.0,3.0,59000.0
2,3.0,25-30,4.0,RedFox,Veg,1322.0,2.0,30000.0
3,4.0,20-25,4.0,LemonTree,Veg,1234.0,2.0,120000.0
4,5.0,35+,3.0,Ibis,Veg,989.0,2.0,45000.0
5,6.0,35+,3.0,Ibis,Non-Veg,1909.0,2.0,122220.0
6,7.0,35+,4.0,RedFox,Veg,1000.0,2.0,21122.0
7,8.0,20-25,4.0,LemonTree,Veg,2999.0,2.0,345673.0
8,9.0,25-30,2.0,Ibis,Non-Veg,3456.0,3.0,96755.0
9,10.0,30-35,5.0,RedFox,Non-Veg,6755.0,4.0,87777.0